{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubeintel.fullname" . }}
  labels:
    {{- include "kubeintel.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kubeintel.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector:
        matchLabels:
          app: authorized-client
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  # Allow HTTPS for AWS API calls
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow Kubernetes API access
  - to: []
    ports:
    - protocol: TCP
      port: 6443
  {{- end }}
{{- end }}