{{- if or .Values.aws.accessKeyId .Values.aws.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeintel.fullname" . }}-aws-credentials
  labels:
    {{- include "kubeintel.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.aws.accessKeyId }}
  access-key-id: {{ .Values.aws.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.secretAccessKey }}
  secret-access-key: {{ .Values.aws.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.sessionToken }}
  session-token: {{ .Values.aws.sessionToken | b64enc | quote }}
  {{- end }}
{{- end }}
